runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: img

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
